### ISSUE TITLE
Upload CDM | LDM | PDM

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#15]
Upload your folder with your name on it ASAP https://github.com/G915-2-Data-Modeling-381/Project-1-eStreamingMovies/tree/main/Model_Highlights

**Comment by oliverVidalCs** [comment]
![Image](https://user-images.githubusercontent.com/112995928/193505368-c573fa9e-6d09-4114-a878-1cb82906e58a.jpg)
![Image](https://user-images.githubusercontent.com/112995928/193505371-94dc43ec-9175-4bce-a464-3e719dc6de62.jpg)
![Image](https://user-images.githubusercontent.com/112995928/193505370-6c2fa401-781a-4f25-a035-0b79ec76de3a.jpg)
![Image](https://user-images.githubusercontent.com/112995928/193505369-3d759537-4d89-491d-852c-a13667df2bbf.jpg)

**Comment by oliverVidalCs** [comment]
Uploaded my CDM, LDM, PDM for my project.

Summary:

-Has the previous old rental existing model 

-With the addition of the modernized streaming service, that contains the entities MovieDigitalCopy, MovieStreamingRecord, MovieStreamingService, customerService

-Made some modifications to the existing rental models to allow for a coexisting of data with the modernized services. Such as allowing the user to input more than one credit card, updated payment attributes, etc.
