### ISSUE TITLE
Write definitions & attributes for Payment, Customer, Subscription

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#26]

**Comment by tom11322** [comment]
Payment: A method the customer pays to buy a subscription.
Customer: A person that buy a subscription.
Subscription: A rental of a movie that the company own.

**Comment by tom11322** [comment]
Payment:
PaymentID (PK)
PaymentAmount
PaymentDate
CustomerID (FK)
PaymentType

**Comment by tom11322** [comment]
Customer:
CustomerID (PK)
PersonID (FK)
Preference*
Tier

**Comment by ambergarcia** [comment]
confirmed
