### ISSUE TITLE
Write Definitions and attributes for Person and Address

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#29]

**Comment by jaga41** [comment]
**Conceptual Data Model**

Business Objects:
     Person: A single human being.
     Address: Where a Person lives.

Business Rules:
     A Person has an Address & an Address belongs to a Person.

**Logical Data Model**

Entity: Attributes (key attributes are above the line) & Relationships –

     Address: 
     Address Id 
     ____________
     Address State 
     Address City 
     Address Zip Code
     Address Street

     Person: 
     Person Id
     ___________
     Person First Name 
     Person Last Name
     Person Phone Number
     Person Email Address
     Address Id (Foreign Key referencing Address.AddressId)
