### ISSUE TITLE
Write definitions & attributes for Employee and Customer Service

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#30]

**Comment by oliverVidalCs** [comment]
**Employee**

EmployeeNumber PK
Supervisor FK
EmployeeAddress 
EmployeeAddress2
EmployeePhone
HireDate
Salary
Position
Email
StoreNumber


CustomerService

ServiceRequestNumber PK
AccountNumber FK
EmployeeNumbers FK
Report FK
EmployeeReport
TicketStatus
CustomerSurvey
