### ISSUE TITLE
10/7/2022 4:00PM - Model the PDM

### ISSUE THREAD

**Issue by adrianmnh** [G915-2-Data-Modeling-381/Project-1-eStreamingMovies#32]
GOAL: Put together the physical model

Attendance:

- [x] Amber Garcia
- [x] Adrian Noa
- [x] Jasminder Garcha
- [ ] Wade Li
- [x] Oliver Vidal

To-Dos:

- [x] Compile individual model entities, attributes and domains into main model
- [ ] come up with color palette ideas for the models

Notes:

**Comment by ambergarcia** [comment]
Wade's model elements still need to be added in. We still need:

- [ ] Constraints
- [ ] Data Masking
- [ ] Defaults
